import React, { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { gql, useQuery } from "@apollo/client";
import MovieCard from "../components/MovieCard";
import Layout from "../components/Layout";

const TRENDING_MOVIES = gql`
  query topTrendingMovies($timeWindow: String!, $limit: Int!) {
    topTrendingMovies(time_window: $timeWindow, limit: $limit) {
      original_title
      original_language
      release_date
      poster_path
      overview
      id
      revenue
      vote_average
      vote_count
      genres {
        name
      }
    }
    mediaConfig {
      secure_base_url
      poster_sizes
    }
  }
`;

export default function Home() {
  const [config, setConfig] = useState({});
  const { loading, error, data } = useQuery(TRENDING_MOVIES, {
    variables: { timeWindow: "day", limit: 20 },
  });

  if (loading) return "Loading...";
  if (error) return "Error connecting to the server...";

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-gray-50 dark:bg-gray-900">
        <section className="relative container mx-auto">
          <header className="sticky top-0 py-4 bg-gray-50 dark:bg-gray-900 z-50">
            <h2 className="text-2xl font-bold dark:text-gray-100">
              Top 20 Trending Movies Today
            </h2>
          </header>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {data?.topTrendingMovies?.map((movie) => {
              return (
                <MovieCard
                  key={movie.key}
                  movie={movie}
                  mediaConfig={data.mediaConfig}
                />
              );
            })}
          </div>
        </section>
      </main>
    </Layout>
  );
}
